export const COPY = {
  es: {
    carta: "Carta",
    hours: "Horarios",
    mesa: "Mesa",
    search: "Buscar un plato",
    noMatch: "No hay platos con ese nombre.",
    empty: "No hay productos disponibles para mostrar.",
    send: "Enviar a cocina",
    sending: "Enviando…",
    inOrder: "En el pedido",
    note: "Observación",
    noteHint: "opcional",
    notePh: "Ej: sin cebolla, bien cocido…",
    close: "Cerrar",
    add: "Sumar",
    remove: "Quitar",
    themeToLight: "Pasar a modo claro",
    themeToDark: "Pasar a modo oscuro",
    langToEn: "Cambiar a inglés",
    langToEs: "Cambiar a español",
    categories: "Categorías",
    filters: "Filtros rápidos",
    vegetariano: "Vegetariano",
    sintacc: "Sin TACC",
    picante: "Picante",
    whatsapp: "Consultar por WhatsApp",
    waPrefill: "Hola, quiero consultar por la carta.",
    loading: "Cargando la carta",
    products: "productos"
  },
  en: {
    carta: "Menu",
    hours: "Hours",
    mesa: "Table",
    search: "Search a dish",
    noMatch: "No dishes match that name.",
    empty: "There are no dishes to show.",
    send: "Send to kitchen",
    sending: "Sending…",
    inOrder: "In your order",
    note: "Note",
    noteHint: "optional",
    notePh: "E.g. no onion, well done…",
    close: "Close",
    add: "Add",
    remove: "Remove",
    themeToLight: "Switch to light mode",
    themeToDark: "Switch to dark mode",
    langToEn: "Switch to English",
    langToEs: "Switch to Spanish",
    categories: "Categories",
    filters: "Quick filters",
    vegetariano: "Vegetarian",
    sintacc: "Gluten-free",
    picante: "Spicy",
    whatsapp: "Ask on WhatsApp",
    waPrefill: "Hi, I have a question about the menu.",
    loading: "Loading the menu",
    products: "dishes"
  }
};
